### PR TITLE
support for Optional[`a]

### PR DESCRIPTION
**Pull request by tobyink**
Adds support for:

      has foo => Optional[Int];

### CODE REVIEW

**Comment by zoffixznet** [comment]
👍 Thanks!

**Comment by zoffixznet** [comment]
Looks like this broke support for `Maybe`, [like in this piece of code](https://github.com/perl6/modules.perl6.org/blob/9a94f693393b73e671c46769f7b1d954b3b5c5be/lib/ModulesPerl6/DbBuilder.pm#L27)

I'm now getting this for it:

```
$ perl bin/build-project-list.pl
Must be a positive number (in $args->{"limit"}) at (eval 347) line 118
    "PositiveNum" is a subtype of "Num"
    "Num" is a subtype of "LaxNum"
    "LaxNum" is a subtype of "Str"
    "Str" is a subtype of "Value"
    "Value" is a subtype of "Defined"
    Undef did not pass type constraint "Defined" (in $args->{"limit"})
    "Defined" is defined as: (defined($_))
```

Any ideas for how to fix that?

**Comment by tobyink** [comment]
Hmmm, try changing this:

```
if ($mew_type and $mew_type->is_parameterized and $mew_type->parent == Types::Standard::Optional()) {
```

to this:

```
if ($mew_type and $mew_type->is_parameterized and $mew_type->parent->strictly_equals(Types::Standard::Optional)) {
```

And this:

```
elsif ($mew_type and $mew_type == Types::Standard::Optional()) {
```

To this:

```
elsif ($mew_type and $mew_type->strictly_equals(Types::Standard::Optional)) {
```

The overloaded `==` uses a looser version of the equality check which thinks `Maybe` and `Optional` are the same (because they do actually inline to the same thing in most cases).

**Comment by zoffixznet** [comment]
👍 That [did the trick](https://github.com/zoffixznet/Mew/commit/aa15f14df163bf673140d0d71ec3595e1c8b3471). Thanks!

**Pull request merged**
